/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteractiveDeckIndexRouteImport } from './routes/interactive-deck.index'
import { Route as InteractiveDeckDeckIdRouteImport } from './routes/interactive-deck.$deckId'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as InteractiveDeckAdminDeckIdRouteImport } from './routes/interactive-deck.admin.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDeckIndexRoute = InteractiveDeckIndexRouteImport.update({
  id: '/interactive-deck/',
  path: '/interactive-deck/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDeckDeckIdRoute = InteractiveDeckDeckIdRouteImport.update({
  id: '/interactive-deck/$deckId',
  path: '/interactive-deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDeckAdminDeckIdRoute =
  InteractiveDeckAdminDeckIdRouteImport.update({
    id: '/interactive-deck/admin/$deckId',
    path: '/interactive-deck/admin/$deckId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck/': typeof InteractiveDeckIndexRoute
  '/interactive-deck/admin/$deckId': typeof InteractiveDeckAdminDeckIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck': typeof InteractiveDeckIndexRoute
  '/interactive-deck/admin/$deckId': typeof InteractiveDeckAdminDeckIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck/': typeof InteractiveDeckIndexRoute
  '/interactive-deck/admin/$deckId': typeof InteractiveDeckAdminDeckIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck/$deckId'
    | '/interactive-deck/$deckId'
    | '/interactive-deck/'
    | '/interactive-deck/admin/$deckId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck/$deckId'
    | '/interactive-deck/$deckId'
    | '/interactive-deck'
    | '/interactive-deck/admin/$deckId'
  id:
    | '__root__'
    | '/'
    | '/deck/$deckId'
    | '/interactive-deck/$deckId'
    | '/interactive-deck/'
    | '/interactive-deck/admin/$deckId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  InteractiveDeckDeckIdRoute: typeof InteractiveDeckDeckIdRoute
  InteractiveDeckIndexRoute: typeof InteractiveDeckIndexRoute
  InteractiveDeckAdminDeckIdRoute: typeof InteractiveDeckAdminDeckIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-deck/': {
      id: '/interactive-deck/'
      path: '/interactive-deck'
      fullPath: '/interactive-deck/'
      preLoaderRoute: typeof InteractiveDeckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-deck/$deckId': {
      id: '/interactive-deck/$deckId'
      path: '/interactive-deck/$deckId'
      fullPath: '/interactive-deck/$deckId'
      preLoaderRoute: typeof InteractiveDeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-deck/admin/$deckId': {
      id: '/interactive-deck/admin/$deckId'
      path: '/interactive-deck/admin/$deckId'
      fullPath: '/interactive-deck/admin/$deckId'
      preLoaderRoute: typeof InteractiveDeckAdminDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  InteractiveDeckDeckIdRoute: InteractiveDeckDeckIdRoute,
  InteractiveDeckIndexRoute: InteractiveDeckIndexRoute,
  InteractiveDeckAdminDeckIdRoute: InteractiveDeckAdminDeckIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
