/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InteractiveDeckIndexRouteImport } from './routes/interactive-deck.index'
import { Route as InteractiveDeckDeckIdRouteImport } from './routes/interactive-deck.$deckId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDeckIndexRoute = InteractiveDeckIndexRouteImport.update({
  id: '/interactive-deck/',
  path: '/interactive-deck/',
  getParentRoute: () => rootRouteImport,
} as any)
const InteractiveDeckDeckIdRoute = InteractiveDeckDeckIdRouteImport.update({
  id: '/interactive-deck/$deckId',
  path: '/interactive-deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck/': typeof InteractiveDeckIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck': typeof InteractiveDeckIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interactive-deck/$deckId': typeof InteractiveDeckDeckIdRoute
  '/interactive-deck/': typeof InteractiveDeckIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/interactive-deck/$deckId' | '/interactive-deck/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/interactive-deck/$deckId' | '/interactive-deck'
  id: '__root__' | '/' | '/interactive-deck/$deckId' | '/interactive-deck/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InteractiveDeckDeckIdRoute: typeof InteractiveDeckDeckIdRoute
  InteractiveDeckIndexRoute: typeof InteractiveDeckIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-deck/': {
      id: '/interactive-deck/'
      path: '/interactive-deck'
      fullPath: '/interactive-deck/'
      preLoaderRoute: typeof InteractiveDeckIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interactive-deck/$deckId': {
      id: '/interactive-deck/$deckId'
      path: '/interactive-deck/$deckId'
      fullPath: '/interactive-deck/$deckId'
      preLoaderRoute: typeof InteractiveDeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InteractiveDeckDeckIdRoute: InteractiveDeckDeckIdRoute,
  InteractiveDeckIndexRoute: InteractiveDeckIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
